### ISSUE TITLE
Failed to connect: GitHub authentication failed: invalid code provided

### ISSUE THREAD

**Issue by Sebelino** [sturdy-dev/sturdy#921]
Hoy there. I am having some trouble connecting my Sturdy project to GitHub. To reproduce:

1. Navigate to the Settings page at https://getsturdy.com/user
2. Click `Connect to GitHub`
3. Click `Authorize Sturdy Devtools`
4. I am taken to a new page with an xdg-open popup. Clicking `Open xdg-open` just opens up a new empty Chrome window. 
![hoy2](https://user-images.githubusercontent.com/837775/160284315-e00de2a5-3ff4-41ad-93ac-3068bda246c6.png)

6. Clicking `continue in browser` takes me to the following page: ![hoy](https://user-images.githubusercontent.com/837775/160284302-2d367074-b0cb-4c04-8d7e-ae77e30d777f.png)

Login URL:
```
https://github.com/login/oauth/authorize?client_id=Iv1.7166a6dda97db2e0&state=web-%2Fuser
```
Error page URL:
```
https://getsturdy.com/setup-github?code=(20-char hexadecimal string)&state=web-%2Fuser
```

Client: Web
Server: Cloud
Browser: Google Chrome Version 99.0.4844.51 (Official Build) (64-bit)
OS: Mint
```
$ uname -a                                                  
Linux sebelino-ThinkPad-P43s 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

I get the same behavior in the Linux desktop app as well, where the login URL is a little different:
```
https://github.com/login/oauth/authorize?client_id=Iv1.7166a6dda97db2e0&state=app-%2Fuser&redirect_uri=sturdy%3A%2F%2F%2Fsetup-github
```

**Comment by zegl** [comment]
Hej @Sebelino 👋 nice to see you here!

I've looked into this, and found that the root cause is that the GitHub account is already connected to another Sturdy account (you probably know which one, if not – send me a DM).

Sturdy _should_ give you an error message about this, but it seems like the error message is getting lost somewhere between all of the redirects and prompts to open the app... 😓 

Have a nice Sunday! 😄

**Comment by Sebelino** [comment]
Ah yes, that makes sense; I had signed up with my business email earlier. Thanks!
