### ISSUE TITLE
Multiple commits (or alternative workflow)

### ISSUE THREAD

**Issue by soanvig** [sturdy-dev/sturdy#923]
Is it possible to create multiple commits? It happens, that during one "flow" in one workspace I'm doing few things, that I would like to have commits for to properly trigger for example semantic release. Currently I see that Sturdy is working on one commit basically all the time.

Side note: Maybe I'm trying to fit Sturdy flow into different flows I know, but currently I have the feeling, that completely obliteraing normal Git flow is actually a suicide, because it kills many possibilities.

**Comment by ngalaiko** [comment]
Hi @soanvig 

We have a docs page about it that you might want to check out https://getsturdy.com/docs/how-to-ship-software-to-production. It also might be not very clear, in that case please let us know 😅 

In general, Sturdy encourages small atomic changes - and that is exactly what Draft Changes (previously named Workspaces) are. So, a natural workflow for Sturdy is Trunk Based Development, rather than a GitFlow.

In your case, multiple commits would mean creating and sharing multiple Draft Changes. When you share a change, Strurdy puts you on top of the trunk and you can keep working on the next one.

If you end up in a situation when you want to share part of the Draft - which sometimes happens - you can use `Copy to New Draft` functionality by selecting diff hunks that you want to copy, and pressing the button. It will produce a new Draft change with selected hunks that you can share separately.

**Comment by soanvig** [comment]
Thanks, that makes sense
